<a href="https://colab.research.google.com/github/shraddhas-20/dataCleaningPD/blob/main/titanic_dummies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Nominal Data = One- hot encoding

#Ordinal data = ordinal encoding

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic (2).csv

In [ ]:
titanic = pd.read_csv('titanic.csv')
titanic

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
titanic = pd.get_dummies(titanic, columns=['Sex'], drop_first = True)

In [ ]:
titanic

,PassengerId,Name,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Sex_male
0,1,"Braund, Mr. Owen Harris",3,22.0,1,0,A/5 21171,7.2500,NaN,S,0,True
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,3,"Heikkinen, Miss. Laina",3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,False
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,1,False
4,5,"Allen, Mr. William Henry",3,35.0,0,0,373450,8.0500,NaN,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,27.0,0,0,211536,13.0000,NaN,S,0,True
887,888,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,1,False
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,False
889,890,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C,1,True
890,891,"Dooley, Mr. Patrick",3,32.0,0,0,370376,7.7500,NaN,Q,0,True

In [ ]:
titanic

,PassengerId,Name,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived,Sex_male
0,1,"Braund, Mr. Owen Harris",3,22.0,1,0,A/5 21171,7.2500,NaN,S,0,True
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,1,False
2,3,"Heikkinen, Miss. Laina",3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,False
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,1,False
4,5,"Allen, Mr. William Henry",3,35.0,0,0,373450,8.0500,NaN,S,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",2,27.0,0,0,211536,13.0000,NaN,S,0,True
887,888,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,1,False
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",3,NaN,1,2,W./C. 6607,23.4500,NaN,S,0,False
889,890,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,C148,C,1,True
890,891,"Dooley, Mr. Patrick",3,32.0,0,0,370376,7.7500,NaN,Q,0,True

In [ ]:
#feature and target

X = titanic[['Age', 'Pclass', 'Sex_male']]

#Target
y = titanic['Survived']

print (X.shape, y.shape) #891 rows and 3 columns in X (feature), 891 rows and 1 columns in y(target)

(891, 3) (891,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.2, random_state= 42)

In [ ]:
X_train.shape

(178, 3)

In [ ]:
X_test.shape

(713, 3)